import * as React from "react";
import {
  Body,
  Button,
  Container,
  Head,
  Hr,
  Html,
  Link,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import { EmailFooter } from "./EmailFooter.js";

/**
 * MagicLinkEmail — Phase Nova-2 React-Email template.
 *
 * Linear/Vercel aesthetic: pitch-black background, hairline borders, monospace
 * for IP + UA + URL, single primary CTA. Plain-text fallback is generated by
 * `render(..., { plainText: true })` in `renderMagicLink`.
 */

export interface MagicLinkEmailProps {
  url: string;
  expiresInMinutes: number;
  /** Optional — surfaces in body so users can spot suspicious requests. */
  requestIp?: string;
  /** Optional — same purpose as `requestIp`. */
  userAgent?: string;
}

const BG = "#0a0a0c";
const SURFACE = "#111114";
const BORDER = "#222226";
const TEXT = "#fafafa";
const MUTED = "#888892";

export function MagicLinkEmail({
  url,
  expiresInMinutes,
  requestIp,
  userAgent,
}: MagicLinkEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>{`Your link expires in ${expiresInMinutes} minutes`}</Preview>
      <Body
        style={{
          backgroundColor: BG,
          fontFamily:
            'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif',
          margin: 0,
          padding: "32px 0",
        }}
      >
        <Container
          style={{
            backgroundColor: SURFACE,
            border: `1px solid ${BORDER}`,
            borderRadius: 6,
            maxWidth: 480,
            padding: "32px 28px",
          }}
        >
          <Text
            style={{
              color: TEXT,
              fontSize: 14,
              fontFamily:
                'ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace',
              letterSpacing: "0.04em",
              margin: "0 0 24px",
            }}
          >
            ▸ ValidationKit
          </Text>

          <Text
            style={{
              color: TEXT,
              fontSize: 18,
              fontWeight: 600,
              letterSpacing: "-0.01em",
              margin: "0 0 12px",
            }}
          >
            Sign in to ValidationKit
          </Text>

          <Text
            style={{ color: MUTED, fontSize: 14, lineHeight: 1.6, margin: "0 0 24px" }}
          >
            Click the button below to finish signing in. The link works once and
            expires in {expiresInMinutes} minutes.
          </Text>

          <Section style={{ margin: "0 0 24px" }}>
            <Button
              href={url}
              style={{
                backgroundColor: TEXT,
                color: BG,
                borderRadius: 6,
                fontSize: 14,
                fontWeight: 500,
                padding: "10px 20px",
                textDecoration: "none",
              }}
            >
              Sign in
            </Button>
          </Section>

          <Text
            style={{ color: MUTED, fontSize: 12, lineHeight: 1.6, margin: "0 0 8px" }}
          >
            Or paste this URL into your browser.
          </Text>
          <Text
            style={{
              color: TEXT,
              fontSize: 11,
              fontFamily:
                'ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace',
              wordBreak: "break-all",
              margin: "0 0 24px",
            }}
          >
            <Link href={url} style={{ color: TEXT, textDecoration: "underline" }}>
              {url}
            </Link>
          </Text>

          <Hr style={{ borderColor: BORDER, margin: "24px 0" }} />

          {requestIp || userAgent ? (
            <Section style={{ margin: "0 0 16px" }}>
              <Text
                style={{
                  color: MUTED,
                  fontSize: 11,
                  fontFamily:
                    'ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace',
                  lineHeight: 1.6,
                  margin: 0,
                }}
              >
                {requestIp ? <>Requested from {requestIp}</> : null}
                {requestIp && userAgent ? " · " : null}
                {userAgent ? <>UA: {userAgent}</> : null}
              </Text>
            </Section>
          ) : null}

          <Text style={{ color: MUTED, fontSize: 11, lineHeight: 1.6, margin: 0 }}>
            If you didn&apos;t request this email, you can safely ignore it. No
            account is created until you click the link.
          </Text>

          <EmailFooter />
        </Container>
      </Body>
    </Html>
  );
}
