"use server";

import path from "node:path";
import { and, desc, eq } from "drizzle-orm";
import { updateTag } from "next/cache";
import { getDb, isDbEnabled, schema } from "@vk/db";
import { dispatchPR, LocalGitClient } from "@vk/pr-workflow";
import { galaxieWorkspaceTag } from "./cache-tags";
import { userIsMember } from "./authz";
import { getSessionUser } from "./session";
import {
  isGitHubAppConfigured,
  resolveApplyMode,
  snoozeDurationToDate,
  isValidDismissReason,
  type ApplyMode,
  type DismissReason,
} from "./apply-mode";

export interface ApplyResult {
  ok: boolean;
  applyActionId?: string;
  mode?: ApplyMode;
  targetUrl?: string;
  targetRef?: string;
  targetStatus?: string;
  error?: string;
}

const LOCAL_PATCH_DIR =
  process.env.VK_LOCAL_PATCH_DIR ?? "/tmp/vk-patches";

export async function applySolution(
  userId: string,
  solutionId: string,
): Promise<ApplyResult> {
  if (!isDbEnabled()) return { ok: false, error: "DB not configured." };
  const db = getDb();

  // Load solution + chain (finding → scan → repo → customer → workspace).
  // Sprint G5 — tolerate legacy scans where scan.repo_id is NULL by falling
  // back to scan.rootPath = repo.rootPath in the same workspace.
  const baseRows = await db
    .select({
      solution: schema.solution,
      finding: schema.finding,
      scan: schema.scan,
    })
    .from(schema.solution)
    .innerJoin(schema.finding, eq(schema.solution.findingId, schema.finding.id))
    .innerJoin(schema.scan, eq(schema.finding.scanId, schema.scan.id))
    .where(eq(schema.solution.id, solutionId))
    .limit(1);
  const base = baseRows[0];
  if (!base) {
    return { ok: false, error: "Solution not found." };
  }

  // Resolve repo via scan.repoId or rootPath fallback.
  const repoRows = await db
    .select()
    .from(schema.repo)
    .where(
      base.scan.repoId
        ? eq(schema.repo.id, base.scan.repoId)
        : and(
            eq(schema.repo.workspaceId, base.scan.workspaceId),
            eq(schema.repo.rootPath, base.scan.rootPath),
          ),
    )
    .limit(1);
  const repoRow = repoRows[0];
  if (!repoRow) {
    return { ok: false, error: "No repo links to this finding's scan." };
  }
  if (!repoRow.customerId) {
    return { ok: false, error: "Repo has no customer assigned." };
  }
  const customerRows = await db
    .select()
    .from(schema.customer)
    .where(eq(schema.customer.id, repoRow.customerId))
    .limit(1);
  const customerRow = customerRows[0];
  if (!customerRow) {
    return { ok: false, error: "Customer not found for this repo." };
  }
  const row = {
    solution: base.solution,
    finding: base.finding,
    scan: base.scan,
    repo: repoRow,
    customer: customerRow,
  };

  if (!(await userIsMember(row.scan.workspaceId, userId))) {
    return { ok: false, error: "Not authorized." };
  }
  if (row.solution.status !== "ready" || !row.solution.patch) {
    return { ok: false, error: "Solution is not ready." };
  }

  const intent = resolveApplyMode(
    row.customer.defaultApplyMode,
    row.repo.applyMode,
  );
  const githubConfigured = isGitHubAppConfigured();
  const effectiveMode: ApplyMode = githubConfigured ? intent : "local";

  // Write-access enforcement (GitHub-App + direct or PR both require it).
  if (effectiveMode !== "local" && !row.repo.writeAccessGranted) {
    return {
      ok: false,
      error:
        "Repo is in read-only mode. Request write access before applying.",
    };
  }

  // Build PR dispatch input.
  const shortId = row.finding.id.slice(0, 8);
  const input = {
    repo: row.repo.githubFullName ?? row.repo.rootPath,
    branch: `vk/fix/${shortId}`,
    title: `fix: ${row.finding.title}`,
    body:
      (row.solution.rationale ?? "") +
      "\n\n---\n_Generated by ValidationKit · finding " +
      row.finding.id +
      "_",
    patch: row.solution.patch,
  };

  let dispatchUrl: string;
  let dispatchRef: string;
  let dispatchStatus: string;
  try {
    if (effectiveMode === "local") {
      const client = new LocalGitClient(
        path.join(LOCAL_PATCH_DIR, row.scan.workspaceId),
      );
      const result = await dispatchPR({
        client,
        access: { rootPath: row.repo.rootPath, writeAccessGranted: true },
        input,
      });
      dispatchUrl = result.url;
      dispatchRef = result.ref;
      dispatchStatus = "n/a";
    } else {
      // GitHub-App path — currently throws by stub; surface a clear error.
      // (G6 / Sprint 0.11 wires this properly.)
      return {
        ok: false,
        error:
          "GitHub-App dispatch is not wired yet — set GITHUB_APP_ID etc., then re-try. Until then, customer.default_apply_mode='pr' will fall back to local-patch mode (see env override).",
      };
    }
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  }

  const inserted = await db
    .insert(schema.applyAction)
    .values({
      solutionId: row.solution.id,
      findingId: row.finding.id,
      repoId: row.repo.id,
      workspaceId: row.scan.workspaceId,
      mode: effectiveMode,
      decision: "apply",
      targetUrl: dispatchUrl,
      targetRef: dispatchRef,
      targetStatus: dispatchStatus,
      decidedBy: userId,
    })
    .returning({ id: schema.applyAction.id });

  updateTag(galaxieWorkspaceTag(row.scan.workspaceId));

  return {
    ok: true,
    applyActionId: inserted[0]?.id,
    mode: effectiveMode,
    targetUrl: dispatchUrl,
    targetRef: dispatchRef,
    targetStatus: dispatchStatus,
  };
}

export async function dismissFinding(
  userId: string,
  findingId: string,
  reason: string,
): Promise<ApplyResult> {
  if (!isDbEnabled()) return { ok: false, error: "DB not configured." };
  if (!isValidDismissReason(reason)) {
    return { ok: false, error: `Invalid reason: ${reason}` };
  }
  const db = getDb();
  const findingRows = await db
    .select({ finding: schema.finding, scan: schema.scan })
    .from(schema.finding)
    .innerJoin(schema.scan, eq(schema.finding.scanId, schema.scan.id))
    .where(eq(schema.finding.id, findingId))
    .limit(1);
  const row = findingRows[0];
  if (!row) return { ok: false, error: "Finding not found." };
  if (!(await userIsMember(row.scan.workspaceId, userId))) {
    return { ok: false, error: "Not authorized." };
  }

  await db
    .update(schema.finding)
    .set({
      dismissStatus: "dismissed",
      dismissReason: reason as DismissReason,
      snoozedUntil: null,
    })
    .where(eq(schema.finding.id, findingId));

  await db.insert(schema.applyAction).values({
    findingId,
    workspaceId: row.scan.workspaceId,
    mode: "n/a",
    decision: "dismiss",
    reason,
    decidedBy: userId,
  });

  updateTag(galaxieWorkspaceTag(row.scan.workspaceId));
  return { ok: true };
}

export async function undoDismiss(
  userId: string,
  findingId: string,
): Promise<ApplyResult> {
  if (!isDbEnabled()) return { ok: false, error: "DB not configured." };
  const db = getDb();
  const findingRows = await db
    .select({ finding: schema.finding, scan: schema.scan })
    .from(schema.finding)
    .innerJoin(schema.scan, eq(schema.finding.scanId, schema.scan.id))
    .where(eq(schema.finding.id, findingId))
    .limit(1);
  const row = findingRows[0];
  if (!row) return { ok: false, error: "Finding not found." };
  if (!(await userIsMember(row.scan.workspaceId, userId))) {
    return { ok: false, error: "Not authorized." };
  }

  await db
    .update(schema.finding)
    .set({
      dismissStatus: "active",
      dismissReason: null,
      snoozedUntil: null,
    })
    .where(eq(schema.finding.id, findingId));

  await db.insert(schema.applyAction).values({
    findingId,
    workspaceId: row.scan.workspaceId,
    mode: "n/a",
    decision: "undo-dismiss",
    decidedBy: userId,
  });

  updateTag(galaxieWorkspaceTag(row.scan.workspaceId));
  return { ok: true };
}

export async function snoozeFinding(
  userId: string,
  findingId: string,
  duration: "24h" | "7d" | "forever",
): Promise<ApplyResult> {
  if (!isDbEnabled()) return { ok: false, error: "DB not configured." };
  const db = getDb();
  const findingRows = await db
    .select({ finding: schema.finding, scan: schema.scan })
    .from(schema.finding)
    .innerJoin(schema.scan, eq(schema.finding.scanId, schema.scan.id))
    .where(eq(schema.finding.id, findingId))
    .limit(1);
  const row = findingRows[0];
  if (!row) return { ok: false, error: "Finding not found." };
  if (!(await userIsMember(row.scan.workspaceId, userId))) {
    return { ok: false, error: "Not authorized." };
  }

  const until = snoozeDurationToDate(duration);
  await db
    .update(schema.finding)
    .set({
      dismissStatus: "snoozed",
      snoozedUntil: until,
      dismissReason: null,
    })
    .where(eq(schema.finding.id, findingId));

  await db.insert(schema.applyAction).values({
    findingId,
    workspaceId: row.scan.workspaceId,
    mode: "n/a",
    decision: "snooze",
    snoozeUntil: until,
    decidedBy: userId,
  });

  updateTag(galaxieWorkspaceTag(row.scan.workspaceId));
  return { ok: true };
}

export interface ApplyActionRow {
  id: string;
  mode: string;
  decision: string;
  reason: string | null;
  targetUrl: string | null;
  targetRef: string | null;
  targetStatus: string | null;
  snoozeUntil: Date | null;
  decidedAt: Date;
}

export async function listApplyActionsForFinding(
  findingId: string,
): Promise<ApplyActionRow[]> {
  if (!isDbEnabled()) return [];
  const db = getDb();
  // K11: gate by session-membership. Resolve the owning workspace
  // (finding → scan) and verify the caller is a member before returning the
  // apply history; empty array on denial.
  const user = await getSessionUser();
  if (!user) return [];
  const findingRows = await db
    .select({ workspaceId: schema.scan.workspaceId })
    .from(schema.finding)
    .innerJoin(schema.scan, eq(schema.finding.scanId, schema.scan.id))
    .where(eq(schema.finding.id, findingId))
    .limit(1);
  const workspaceId = findingRows[0]?.workspaceId;
  if (!workspaceId || !(await userIsMember(workspaceId, user.id))) return [];
  const rows = await db
    .select()
    .from(schema.applyAction)
    .where(eq(schema.applyAction.findingId, findingId))
    .orderBy(desc(schema.applyAction.decidedAt));
  return rows.map((r) => ({
    id: r.id,
    mode: r.mode,
    decision: r.decision,
    reason: r.reason,
    targetUrl: r.targetUrl,
    targetRef: r.targetRef,
    targetStatus: r.targetStatus,
    snoozeUntil: r.snoozeUntil,
    decidedAt: r.decidedAt,
  }));
}

export async function pollPRStatus(
  applyActionId: string,
): Promise<{ state: string } | null> {
  if (!isDbEnabled()) return null;
  const db = getDb();
  const rows = await db
    .select()
    .from(schema.applyAction)
    .where(eq(schema.applyAction.id, applyActionId))
    .limit(1);
  const row = rows[0];
  if (!row) return null;
  if (row.mode !== "pr") return { state: row.targetStatus ?? "n/a" };
  // GitHub-App-Path isn't wired yet (Sprint 0.11). Until then echo back the
  // last-seen status; G5 doesn't introduce live polling here.
  return { state: row.targetStatus ?? "unknown" };
}
